# Generated by Django 6.0.7 on 2026-08-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0002_comunidad_gestores'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='logo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
